### ISSUE TITLE
refactor ingress

### ISSUE THREAD

**Issue by whitlockjc** [30x/k8s-pods-ingress#11]
Based on recent feedback and such, we need to refactor the ingress:

- [x] Allow exposing multiple _services_ per deployment _(right now you can only expose one container port for all host+path combinations)_
- [x] Make the label selector for identifying _"microservices"_ configurable along with the annotation names used
- [x] Rename the annotations/labels _(we should use k8s, or more general, names where possible)_
- [x] Support an optional _API Key (stored in k8s as a secret with a specific name)_ _(This solves a specific use case internally and the eventual replacement is a real authn/authz layer)_

**Comment by whitlockjc** [comment]
To expose multiple _"services"_ per deployment, I think we need to update the `publicPaths` annotation to continue using a space-delimited list of paths but instead of a simple `path`, the value would now be `port:path`.  So if I wanted to expose two different paths, each serviced by different containers within the same path, I might have have something like this: `publicPaths: 8080:/java 3000:/nodejs`

**Comment by whitlockjc** [comment]
To handle the optional _API Key_, my suggestion is that whenever a namespace has an `ingress-api-key` secret, we enable a header check in nginx for all pods within that namespace.  This check will make sure that the value of the `ingress-api-key` secret matches the `X-INGRESS-API-KEY` header value in the request.

**Comment by tnine** [comment]
I agree with this.  It's up to the caller to create, retain, and pass the key at runtime.  We don't want to get into the business of secret storage.  Storing it in the namespace is the only persistence we want.  To be clear we need to make the following changes.

- [] In the deploy service, this secret will be specified on POST.  It can also be specified on PATCH
- [] The caller will have to set the ```X-INGRESS-API-KEY``` header during invocation

**Comment by whitlockjc** [comment]
To rename the annotations/labels, these are the changes I would propose:

* `trafficHosts` -> `ingressHosts`
* `publicPaths` -> `ingressPublicPaths` _(I know it's a little wordy but the idea is to be immediately intuitive)_

**Comment by tnine** [comment]
Works for me

**Comment by jbowen93** [comment]
For deployment flow clarity on whether there can be multiple `ingressHosts` and/or `ingressPublicPaths` would be appreciated. I have no issue with the rename.

**Comment by whitlockjc** [comment]
@jbowen93 I don't follow.  Each Pod now can have one `trafficHosts`/`ingressHosts` annotation and one `publicPaths`/`ingressPublicPaths` annotation.  Its values is a space-delimited list of values.  So if you want multiple hosts, `trafficHosts: host1.github.com host2.github.com` and if you want multiple services, `publicPaths: 3000:/nodejs 8080:/java`.  Did that help?

**Comment by jbowen93** [comment]
That cleared it up. Thanks.

**Comment by mpnally** [comment]
makes sense to me. Is ingressPublicPaths redundant? Can an ingress path be private? If not, can we simplify to ingressPath and privatePath?

**Comment by mpnally** [comment]
Or ingressPaths and internalPaths?

**Comment by whitlockjc** [comment]
Good point.  It could be `ingressPaths` for the public -> k8s routing and when we do private paths, maybe they'll be called `servicePaths` or something.  The `ingress*` part of these annotations was really a way to _"namespace"_ the annotations but maybe we don't need them?

**Comment by whitlockjc** [comment]
The next thing we will tackle is making this ingress a little more general purpose.  Right now, it's been developed that the labels/annotations are hard coded and while that's fine, it makes supporting other scenarios harder.  Let's say you wanted your ingress to have a public-facing side and a private-facing side.  To do this with the ingress as-is would require direct support in the ingress for something like a `privatePaths` annotation on your pods.  But the real meat of the ingress itself hasn't changed.  So by making the _configuration_ items for the ingress itself configurable, you could just instead deploy two different ingress containers with one configured for public-facing and another configured for private-facing.

Here is the proposal:

* Make the `microservices` label really just a k8s [label selector](http://kubernetes.io/docs/user-guide/labels/#label-selectors) that is provided via the `INGRESS_LABEL_SELECTOR` environment variable _(environment variable name not set in stone)_
* Make it so the name of the `publicPaths` annotation is itself configurable via the `INGRESS_PATHS_ANNOTATION` environment variable _(environment variable name not set in stone)_
* Make it so the name of the `trafficHosts` annotation is itself configurable via the `INGRESS_HOSTS_ANNOTATION` environment variable _(environment variable name not set in stone)_

**Comment by mpnally** [comment]
Can you say more about the meaning of the environment variables? I think
`INGRESS_PATHS_ANNOTATION` is the name of the annotation in the PTS for that paths. In our current scenarios, the value would be either `public_paths` or `private_paths`. I think `INGRESS_HOSTS_ANNOTATION` is similar - the name of the ReplicaSet annotation that holds the hostname that its pods will accept traffic from. `INGRESS_LABEL_SELECTOR` is the name of the pod label used to indicate whether or not the pod is one that the ingress controller needs to care about. For some reason, I'm struggling more with `INGRESS_SECRET_FIELD_NAME` and `INGRESS_SECRET_NAME`

**Comment by whitlockjc** [comment]
Right, based on the proposal, here are the meenings:

* `INGRESS_HOSTS_ANNOTATION` _(The current value is `trafficHosts`)_: This is the annotation name on the pod that will contain the _"traffic hosts"_
* `INGRESS_LABEL_SELECTOR` _(The current value is `microservice=true`)_: This is the label selector that is used to identify pods we're interested in routing to _(right now, the ingress works only with Pods but will soon be updated to work with  Deployments/ReplicationControllers/ReplicaSets via subtask number 3)_
* `INGRESS_PATHS_ANNOTATION` _(The current value is `publicPaths`)_: This is the annotation name on the pod that will contain the `{CONTAINER_PORT}:{PATH}` values that are used to map request paths to container ports
* `INGRESS_SECRET_NAME` _(The current value is `ingress`)_: This is the secret name used for storing ingress-related secrets
* `INGRESS_SECRET_FIELD_NAME` _(The current value is `api-key`)_: This is the name of the data field within the `ingress` secret

**Comment by mpnally** [comment]
To me, ingress implies that the requests are coming from outside the
cluster and entering the cluster. Merriam webster says ingress means "a way
to enter a place or the act of entering a place". When we are doing
microservice-to-microservice, this metaphor doesn't seem so appropriate to
me.

Martin

**Comment by mpnally** [comment]
could ingress_secret_name and ingress_secret_field_name be collapsed to a single value with an a.b format? Then we only need one name. I worry a little we are overusing the word ingress. If it is not about entering somewhere, we should not attach the word ingress to it.

**Comment by whitlockjc** [comment]
@mpnally Answers below:

1. I agree but the original intent of this thing was to provide an ingress, a routing between an externally-requested host+path combination that maps to an internal k8s pod or pods.  We _(internally)_ are wanting to repurpose this ingress as more of a _gateway_ by wanting to do internal-only host+path combinations using the same _ingress product_.  But in the end, the code base is as an ingress...it just so happens that we're making it repurpose-able and some of the cases where we repurpose the ingress aren't really an ingress.

2. Makes sense to me.  I thought about this **after** I wrote this but decided to leave it as-is so people knew all of the touch points.

**Comment by mpnally** [comment]
I don't think that was ever the intent. This was always [the beginnings of]
an API management gateway. We talked about this a lot when we were
discussing whether or not to use K8S own approach to ingress.

Martin

**Comment by whitlockjc** [comment]
@mpnally Well, we've talked about a lot of things and the ingress was just one of the N different parts of the system we've talked about.  We started with an ingress and that's what this tool has been from day one.  Now that we're repurposing it by tacking API management features onto it, we can definitely rename the project and use applicable environment variables.  I don't care enough to argue so if you have suggestions, please provide them.

**Comment by mpnally** [comment]
How about these:
INGRESS_HOSTS_ANNOTATION => REPLICASET_HOSTS_ANNOTATION
INGRESS_LABEL_SELECTOR =>      POD_LABEL_SELECTOR
INGRESS_PATHS_ANNOTATION =>  POD_PATHS_ANNOTATION
INGRESS_SECRET_NAME =>            NAMESPACE_API_KEY_LOCATION
INGRESS_SECRET_FIELD_NAME - retired—part of NAMESPACE_API_KEY_LOCATION

**Comment by whitlockjc** [comment]
I have a few disagreements with explanation below:

* `REPLICASET_HOSTS_ANNOTATION`: Since replica set objects are a result of creating/modifying a deployment object, I would expect that the hosts/weights/... will be set on the deployment.  The reason for this is because once you use a deployment to create the replica sets which in turn create the pods, patching the replica sets would work for running replica sets but would then be overwritten once the replica sets are recreated when the deployment is changed for whatever reason.  I could also see hard coding the scope where this thing lives, like to only deployments, as being problematic as everyone will not be using deployment objects but might use replication controllers and/or replica sets directly.  So we need something generic in name.

* `POD_LABEL_SELECTOR`: This label selector is used to identify both deployments _(in the future as we do not do this now)_ **and** pods.  So like above, I would suggest something generic in name.

* `NAMESPACE_API_KEY_LOCATION`: This is verbose and somewhat redundant because secrets are automatically tied to the namespace so unless we allow you to pull secrets from other namespaces, which we don't and likely won't, we shouldn't mention `NAMESPACE`.

**Comment by whitlockjc** [comment]
I really would like to make it so that we had `ROUTER_LABEL_SELECTOR` and `ROUTER_LABEL_SCOPE=[deployment,pod,replicationcontroller,replicaset]`.  That would be the ultimate because then it's up to you as to where you define your metadata.  That could be slick, although I'm not proposing it now.

**Comment by whitlockjc** [comment]
While working on making the routing touch points configurable, I also went ahead and made the default values for these configurable items more generic, which should address the second sub task.  Here are the changes:

* `trafficHosts` -> `routingHosts`
* `publicPaths` -> `routingPaths`

Now that these annotation names are configurable, the names for these values are more generic and not related to the scope of their purpose, like `private*` and `public*`.

**Comment by mpnally** [comment]
Makes sense. These are the names of the PTS annotations, right? Is there also a new name for privatePaths?

**Comment by whitlockjc** [comment]
@mpnally Until we do the work behind the third subtask, where we break out some of the annotations currently set at the Pod template spec level up to the Deployment/ReplicationController/ReplicaSet, all of this is set on the Pod's template spec.  As for how we'll handle `privatePaths`, take a look at the multipurpose deployment example where this is implemented: https://github.com/30x/k8s-pods-ingress/tree/make-configurable#multipurpose-deployments  If you have comments on this, please respond to #22.

**Comment by whitlockjc** [comment]
#22 has been merged so the link above to the `Multipurpose Deployments` is now on master.

**Comment by whitlockjc** [comment]
All subtasks are complete, closing.  _(I am moving what was subtask 3 to its own issue: #23)_
