### ISSUE TITLE
Change publicPath and privatePath to publicBasePath and privateBasePath respectively

### ISSUE THREAD

**Issue by madhurranjan** [30x/k8s-pods-ingress#28]
Couple of folks had some feedback that publicPath was confusing and hence wanted to be more explicit and make it publicBasePath and privateBasePath. Can you make this change please?

**Comment by whitlockjc** [comment]
That's a deployment configuration so you can use whatever you want.  That was the point of #22, to allow you the ability to use whatever terminology you wanted.
