### ISSUE TITLE
Rethink how we're storing the routing configuration

### ISSUE THREAD

**Issue by whitlockjc** [30x/k8s-pods-ingress#30]
Right now, we're using a mix annotations to perform the wiring of the router.  This is working fine but with #18 and #29, we're quickly getting to the point where we're adding more and more things.  Maybe it's time we look into storing JSON in a single annotation?

**Comment by mpnally** [comment]
What would be the advantage?

**Comment by whitlockjc** [comment]
I created this when I thought we were going to add yet another configuration annotation for #29.  We ended up not doing that so we can keep this in the backlog for now.  But to answer your question, Kubernetes stuff structured data _(JSON)_ into annotations when it makes sense and I think when our routing rules become more complex and/or repetitive, we might want to at least revisit this.  But nothing is changing right now because it's not necessary now that #29 is done without a new annotation.

**Comment by whitlockjc** [comment]
This is not important right now and can be re-opened if/when it ever is.
